openapi: 3.0.0
info:
  title: Initiates alerts migration API endpoint
  version: '2023-10-31'
paths:
  /api/detection_engine/signals/migration:
    post:
      x-labels: [ess]
      operationId: CreateAlertsMigration
      x-codegen-enabled: true
      summary: Initiate a detection alert migration
      deprecated: true
      description: |
        **DEPRECATED.** Legacy API for on-demand reindexing of old `.siem-signals-*` alert indices. Do not build new
        integrations; upgrade the Elastic Stack and rely on product-managed data lifecycle instead.
        **WARNING:** Migrations can be resource intensive and should be planned during a maintenance window.

        Initiate a migration of detection alerts. Migrations are initiated per index. The process is not destructive
        and should not remove existing data, but it can consume significant cluster resources. Plan capacity accordingly.
      tags:
        - Alerts migration API
      requestBody:
        description: Alerts migration parameters
        required: true
        content:
          application/json:
            schema:
              allOf:
                - type: object
                  properties:
                    index:
                      description: Array of index names to migrate.
                      type: array
                      items:
                        type: string
                        format: nonempty
                        minLength: 1
                      minItems: 1
                  required: [index]
                - $ref: '#/components/schemas/AlertsReindexOptions'
            examples:
              singleIndex:
                value:
                  index: [.siem-signals-default-000001]
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  indices:
                    type: array
                    items:
                      oneOf:
                        - $ref: '#/components/schemas/AlertsIndexMigrationSuccess'
                        - $ref: '#/components/schemas/AlertsIndexMigrationError'
                        - $ref: '#/components/schemas/SkippedAlertsIndexMigration'
                required: [indices]
              examples:
                success:
                  value:
                    indices:
                      - index: .siem-signals-default-000001,
                        migration_id: 923f7c50-505f-11eb-ae0a-3fa2e626a51d
                        migration_index: .siem-signals-default-000001-r000016
        400:
          description: Invalid input data response
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '../../../model/error_responses.schema.yaml#/components/schemas/PlatformErrorResponse'
                  - $ref: '../../../model/error_responses.schema.yaml#/components/schemas/SiemErrorResponse'
              examples:
                badRequest:
                  value:
                    statusCode: 400
                    error: Bad Request
                    message: '[request body].index: at least one index name is required to start a migration'
        401:
          description: Unsuccessful authentication response
          content:
            application/json:
              schema:
                $ref: '../../../model/error_responses.schema.yaml#/components/schemas/PlatformErrorResponse'
              examples:
                unauthorized:
                  value:
                    statusCode: 401
                    error: Unauthorized
                    message: "[security_exception\n\tRoot causes:\n\t\tsecurity_exception: unable to authenticate user [elastic] for REST request [/_security/_authenticate]]: unable to authenticate user [elastic] for REST request [/_security/_authenticate]"
        500:
          description: Internal server error response
          content:
            application/json:
              schema:
                $ref: '../../../model/error_responses.schema.yaml#/components/schemas/SiemErrorResponse'
              examples:
                serverError:
                  value:
                    message: Internal Server Error
                    status_code: 500

components:
  schemas:
    AlertsReindexOptions:
      type: object
      properties:
        requests_per_second:
          type: integer
          minimum: 1
          description: The throttle for the migration task in sub-requests per second. Corresponds to requests_per_second on the Reindex API.
        size:
          type: integer
          minimum: 1
          description: Number of alerts to migrate per batch. Corresponds to the source.size option on the Reindex API.
        slices:
          type: integer
          minimum: 1
          description: The number of subtasks for the migration task. Corresponds to slices on the Reindex API.

    AlertsIndexMigrationSuccess:
      type: object
      properties:
        index:
          type: string
        migration_id:
          type: string
        migration_index:
          type: string
      required:
        - index
        - migration_id
        - migration_index

    AlertsIndexMigrationError:
      type: object
      properties:
        index:
          type: string
        error:
          type: object
          properties:
            message:
              type: string
            status_code:
              type: string
          required: [message, status_code]
      required:
        - index
        - error

    SkippedAlertsIndexMigration:
      type: object
      properties:
        index:
          type: string
      required:
        - index
